### ISSUE TITLE
Pytorch Error

### ISSUE THREAD

**Issue by PavithraV0223** [lewis-chinery/Paragraph#4]
Hello, I'm trying use the Paragraph for my pdb files. These below error is persisting unable to fix the error.  
Paragraph/paragraph_pip_env/bin/Paragraph", line 33, in <module>
    sys.exit(load_entry_point('Paragraph==1.0.0', 'console_scripts', 'Paragraph')())
Paragraph/paragraph_pip_env/bin/Paragraph", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/main-SSD04/0.software/anaconda3/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/main-SSD04/0.software/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Paragraph/paragraph_pip_env/lib/python3.9/site-packages/Paragraph-1.0.0-py3.9.egg/Paragraph/command_line.py", line 4, in <module>
    import torch
/Paragraph/paragraph_pip_env/lib/python3.9/site-packages/torch-2.3.0-py3.9-linux-x86_64.egg/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

**Comment by lewis-chinery** [comment]
Hi, I have tested Paragraph using Python 3.8.3. It appears you're using v3.9, so could you first please try recreating the env using the earlier version in case these are torch dependency issues e.g.

`/usr/bin/python3.8 -m venv paragraph_pip_env`

Please follow the rest of install steps as normal after this and let me know if you are still having problems.

**Comment by PavithraV0223** [comment]
Thanks for your response,  I have the 3.8.3 version now. Torch error is persisting  

Processing dependencies for Paragraph==1.0.0
Searching for torch>=1.11
Reading https://pypi.org/simple/torch/
No local packages or working download links found for torch>=1.11
error: Could not find suitable distribution for Requirement.parse('torch>=1.11')

**Comment by lewis-chinery** [comment]
This is a bit tricky to diagnose with the info above - could you provide a few more details?

I've just retried installing this and it works OK for me - I am using Fedora Linux 38. I have tried installing this on Windows before though and that also worked OK. In both cases, neither device had a GPU.

Some small things that could be worth trying if you haven't already:
- upgrade pip before running the install
- install torch in your env manually before running pip install .

**Comment by PavithraV0223** [comment]
I'm on the VS code on Windows 64 bit, using cmd prompt and bash terminal for the CLI interface for Paragraph) 
Pip version 24 
Tired to install manually with the below 
# CPU only
pip install torch==1.11.0+cpu torchvision==0.12.0+cpu torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cpu 
But getting an error again 
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cpu (from versions: none)
ERROR: No matching distribution found for torch==1.11.0+cpu

**Comment by lewis-chinery** [comment]
Have you successfully installed PyTorch before? Perhaps try not specifying the version for now and see if that works (so long as you still have Python 3.8) - https://pytorch.org/get-started/locally/

It looks like there is a 1.11 version for windows on your links though - torch-1.11.0+cpu-cp38-cp38-win_amd64.whl, so I'm not sure why it is not happy with this

**Comment by PavithraV0223** [comment]
I have installed Pytorch earlier but for latest python version. However, I have switched to Linux system now, I see there was a compatible issue with the pytorch and the python version 3.8. When I use the setup.py file torch, scipy was not installing so I did it manually. Still getting some errors like below 
```
VirtualBox:~/Paragraph$ ./test.sh 
Traceback (most recent call last):
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/torch/__init__.py", line 176, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pavi/Paragraph/paragraph_pip_env/bin/Paragraph", line 11, in <module>
    load_entry_point('Paragraph==1.0.0', 'console_scripts', 'Paragraph')()
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/Paragraph-1.0.0-py3.8.egg/Paragraph/command_line.py", line 4, in <module>
    import torch
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/torch/__init__.py", line 236, in <module>
    _load_global_deps()
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/torch/__init__.py", line 197, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/pavi/Paragraph/paragraph_pip_env/lib/python3.8/site-packages/torch/__init__.py", line 163, in _preload_cuda_deps
    ctypes.CDLL(lib_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvJitLink.so.12: cannot open shared object file: No such file or directory

```

**Comment by lewis-chinery** [comment]
Sorry to see you're still having trouble with this. Can I ask what Linux OS are you using now? Would you be able to provide the full error log after running `pip install .` in a clean py3.8 env without installing anything first? Could you also please run `pip install --upgrade pip` after activating your env but before the install and `pip list` before and after the install as well and share all this output?

**Comment by PavithraV0223** [comment]
Sure, Please find the version and the log files for above. 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
[env_pip_install.log](https://github.com/lewis-chinery/Paragraph/files/15163078/env_pip_install.log)
[pip_upgrade.log](https://github.com/lewis-chinery/Paragraph/files/15163080/pip_upgrade.log)

**Comment by PavithraV0223** [comment]
Hey, I managed to get it work now. Probably something to do with the latest version of pytorch. 
Thanks a lot.

**Comment by lewis-chinery** [comment]
I'm glad it works now! If you know what the particular fix was, please do share it here in case it of use to others. (I see that the pip version in your log was not upgraded before you ran the install. With the upgraded version did it work straight away or did you do anything else to fix this?)

**Comment by PavithraV0223** [comment]
I had to install the latest Pytorch and then it worked after the upgradation of the pip. Probably, it might be different for me, not sure.

**Comment by lewis-chinery** [comment]
OK, perfect, thanks for letting me know!
